// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Holds bindings to fibonacci library.
class fibonacci1 {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  fibonacci1(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  fibonacci1.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  int fibonacci(
    int n,
  ) {
    return _fibonacci(
      n,
    );
  }

  late final _fibonacciPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>('fibonacci');
  late final _fibonacci = _fibonacciPtr.asFunction<int Function(int)>();
}
