# dart run ffigen --config ffigen/fibonacci.config.yaml

output: '../lib/ffi/fibonacci_generated_bindings.dart'
name: 'fibonacci'
description: 'Holds bindings to fibonacci library.'
headers:
  entry-points:
    - '../native/fibonacci/fibonacci.h'
  include-directives:
    - '**fibonacci.h'
comments: false